sudo: required

services:
- docker

#env:
#  - DOCKER_COMPOSE_VERSION=1.4.2

addons:
  apt:
    packages:
      - docker-ce

before_install:
#  - sudo apt-get update
#  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
#  - sudo rm -rf /usr/local/bin/docker-compose
#  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#  - chmod +x docker-compose
#  - sudo mv docker-compose /usr/local/bin

secure: "EcLkRKeRGkIgpWo5kfGx99hoJsyxvBswDlEDHUIFrQmDOYvldOC5mERgyx8v/QamkS+tIiF3w1lK/UJ2N8FWg6sEDkj6FIOhdNEgxvP6u3AoFP+lSOZ7AY9TfyOBVgj0mUTPC9zwCluz3WcunNapHl1Cpi3MBM9vZ1J36moTCb/3y9zJw0j+cHfxJJy0BJ+P2yiBn6Qg8nwjtifwKbYmgQ5OKzq/vvGx/1ebZRu93SQd5566hmcRDbH67tWqJELTYzM+hkz8q6TdtDaiHE7icKABZuQY2y5fs4pQaf5kqbCgSo+XSdSEN7RXcSjGWRD1RU2Uf0PxK9U1stQZR6NFW+4XW1nHSaTnxz8QePCDhP4uKfVjspK/bqRcVZA5XUFFlqGUQqyfY/4oiTqhX3GnP9rJTILqG3gWz+6MZrIKHVSGvWVZMVFzjvRw333wo0SRjMTiu3UkVD0rM7Vcl6oTXu/LlwHlrZDIZ1L/uX+Gr2PdsSLU+96/IRfBJdSGQdVtXeQCAtlcTtN4kVz+GlTL/o1WTwuUwe1n5ayi+3fEwkYHgCBPl5CDzbrAGyKuhVST1+wDDOizSk94mfPVm26MGKsCBQB3ZqgOa/w2BTqi/lkpYhaP9fAHs0lrXAuXsNo42O4Q53aak93P5iNIHAuKPamNdsqzCEHwyaxuhGvZhWs="

script:
- travis env set DOCKER_USERNAME daggerok
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker build -t daggerok/jboss-eap-7.1 .
- >
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker tag ${DOCKER_USERNAME}/jboss-eap-7.1 ${DOCKER_USERNAME}/jboss-eap-7.1:latest
    docker tag ${DOCKER_USERNAME}/jboss-eap-7.1 ${DOCKER_USERNAME}/jboss-eap-7.1:alpine
#    docker push ${DOCKER_USERNAME}/jboss-eap-7.1:latest
#    docker push ${DOCKER_USERNAME}/jboss-eap-7.1:alpine
    docker push ${DOCKER_USERNAME}/jboss-eap-7.1
  fi
