services:
- docker
env:
  global:
  - TERM=dumb
  - DOCKER_USERNAME=daggerok
  - DOCKER_IMAGE_NAME=jboss-eap-7.1
  - secure: 28ND4fA1FE1yQY5lw/bwwyrd4fEZkXzgsd/exkoGB8gHI832sWOLhSmkDmfRsONkHWb420NrW0uN4JsyEiqqAuPJuznoCbkeYZzs/DZnx9l0YOn7wBmdlhF1O4Acia1r5Ute3ccVtL97cuih80f2sgdCS6Fy+CAF2qclYYNpKG3bJocbHBVYqLtL4VGqu8uAS9z5XDffCSCX5loQvblQN/Vfl1LZmoa/65zxZxF02fev45JMIiAZRp9z9KTuZZjlmINEMVRndowoZCz+LdidNg2/k6uf7wJ3tMX2O2Cs6lJFYXDv16lINB/Tx/79UJEJKED0uzBHh03KFth903NPYS0NsXo6NrQtEMBWVC3cUkmWWGwHdNhKtL2EGo5L7C3ap886DJg8KrTQpba7C+5ZjXNZ5V8Z8B3RoX0Q1GmrJNcXgqqVaZVM7LXqEw7YvaSWqgC7xnRWo/sqCBNHZNeTeqzOdhG22l1bj2JP8wDVWJECBlmkJfvobkiOsZhB8Zlyb9gEaiYt003l5M/vOeUHOHyrbFVWrxJOH1Tu8Qrwg0e2CIzIEOoQNFwUysZlRgcz7weEHY94bvdIuF53ssjQjlArWKuYbVO52+dC/kNLm8hXue69zyI5mFgZed05ZLAQSlWKh8SA62fVCHM7JJx7ZZ5EIqE+zDA6xpOOin+n8mU=
script:
- docker build -t ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} .
- |
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:alpine
  else
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BRANCH}
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BRANCH}-alpine
  fi
- docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
- docker push ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}
